---
latitude: 40.72403
longitude: -74.00334
map_zoom: 12
name: SIXTY SoHo
email: sgontu@traveltripper.com
phone_number: 001-111-1111
address:
  street1: 60 Thompson Street, Soho
  street2: ''
  state: New York
  city: New York
  country: United States
  zip_code: '10012'
_hotel_id: SIX821
_portal_id: required-but-empty
_root_path: https://rt3api-prd.ttaws.com
